//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace east_india_trading
{
    using System;
    using System.Collections.Generic;
    
    public partial class bandwidth_usage
    {
        public System.DateTime time { get; set; }
        public string database_name { get; set; }
        public string direction { get; set; }
        public string @class { get; set; }
        public string time_period { get; set; }
        public Nullable<decimal> quantity { get; set; }
    }
}
