//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace east_india_trading
{
    using System;
    using System.Collections.Generic;
    
    public partial class billing
    {
        public System.DateTime time { get; set; }
        public string type { get; set; }
        public string database_name { get; set; }
        public string data1 { get; set; }
        public string data2 { get; set; }
        public string data3 { get; set; }
        public string data4 { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public bool billed { get; set; }
        public System.Guid event_id { get; set; }
    }
}
