//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace east_india_trading
{
    using System;
    using System.Collections.Generic;
    
    public partial class database_usage
    {
        public Nullable<System.DateTime> time { get; set; }
        public string sku { get; set; }
        public Nullable<decimal> quantity { get; set; }
    }
}
