//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace east_india_trading
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_database_copies
    {
        public Nullable<int> database_id { get; set; }
        public Nullable<System.DateTimeOffset> start_date { get; set; }
        public Nullable<System.DateTimeOffset> modify_date { get; set; }
        public Nullable<float> percent_complete { get; set; }
        public Nullable<int> error_code { get; set; }
        public string error_desc { get; set; }
        public Nullable<int> error_severity { get; set; }
        public Nullable<int> error_state { get; set; }
        public System.Guid copy_guid { get; set; }
        public string partner_server { get; set; }
        public string partner_database { get; set; }
        public Nullable<byte> replication_state { get; set; }
        public string replication_state_desc { get; set; }
        public Nullable<int> maximum_lag { get; set; }
        public bool is_continuous_copy { get; set; }
        public bool is_target_role { get; set; }
        public bool is_offline_secondary { get; set; }
        public Nullable<bool> is_interlink_connected { get; set; }
    }
}
