//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace east_india_trading
{
    using System;
    using System.Collections.Generic;
    
    public partial class elastic_pool_resource_stats
    {
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public string elastic_pool_name { get; set; }
        public Nullable<decimal> avg_cpu_percent { get; set; }
        public Nullable<decimal> avg_data_io_percent { get; set; }
        public Nullable<decimal> avg_log_write_percent { get; set; }
        public Nullable<decimal> avg_storage_percent { get; set; }
        public Nullable<decimal> max_worker_percent { get; set; }
        public Nullable<decimal> max_session_percent { get; set; }
        public Nullable<int> elastic_pool_dtu_limit { get; set; }
        public Nullable<long> elastic_pool_storage_limit_mb { get; set; }
        public Nullable<decimal> max_xtp_storage_percent { get; set; }
        public Nullable<decimal> avg_login_rate_percent { get; set; }
        public Nullable<decimal> avg_instance_cpu_percent { get; set; }
        public Nullable<decimal> avg_instance_memory_percent { get; set; }
        public Nullable<decimal> elastic_pool_cpu_limit { get; set; }
        public Nullable<decimal> avg_allocated_storage_percent { get; set; }
    }
}
