//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace east_india_trading
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_log
    {
        public string database_name { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public string event_category { get; set; }
        public string event_type { get; set; }
        public int event_subtype { get; set; }
        public string event_subtype_desc { get; set; }
        public int severity { get; set; }
        public int event_count { get; set; }
        public string description { get; set; }
        public string additional_data { get; set; }
    }
}
