//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace east_india_trading
{
    using System;
    using System.Collections.Generic;
    
    public partial class resource_stats_ex
    {
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public string database_name { get; set; }
        public byte[] low_key { get; set; }
        public string sku { get; set; }
        public string resource_capacity { get; set; }
        public Nullable<int> usage_in_seconds { get; set; }
        public Nullable<decimal> storage_in_megabytes { get; set; }
        public Nullable<decimal> max_storage_in_megabytes { get; set; }
    }
}
