//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace east_india_trading
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdac_history_internal
    {
        public int action_id { get; set; }
        public int sequence_id { get; set; }
        public System.Guid instance_id { get; set; }
        public byte action_type { get; set; }
        public string action_type_name { get; set; }
        public byte dac_object_type { get; set; }
        public string dac_object_type_name { get; set; }
        public byte action_status { get; set; }
        public string action_status_name { get; set; }
        public Nullable<bool> required { get; set; }
        public string dac_object_name_pretran { get; set; }
        public string dac_object_name_posttran { get; set; }
        public string sqlscript { get; set; }
        public byte[] payload { get; set; }
        public string comments { get; set; }
        public string error_string { get; set; }
        public string created_by { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
    }
}
