//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace east_india_trading
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdac_instances_internal
    {
        public System.Guid instance_id { get; set; }
        public string instance_name { get; set; }
        public string type_name { get; set; }
        public string type_version { get; set; }
        public string description { get; set; }
        public byte[] type_stream { get; set; }
        public System.DateTime date_created { get; set; }
        public string created_by { get; set; }
    }
}
